[package]
name = "mnist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neural_network_from_scratch = {path = "../../"}
flate2 = "1.0.24"
bytes = "1.1.0"
nalgebra = "0.31.0"